// packages/next-app/pages/users/[id].tsx
import { GetServerSideProps, NextPage } from 'next';

interface User {
  id: string;
  name: string;
  email: string;
}

interface UserPageProps {
  user: User | null;
}

export const getServerSideProps: GetServerSideProps<UserPageProps> = async (context) => {
  const { id } = context.params!;
  try {
    const res = await fetch(`https://api.example.com/users/${id}`);
    const user: User = await res.json();

    return { props: { user } };
  } catch (error) {
    console.error(error);
    return { props: { user: null } };
  }
};

const UserPage: NextPage<UserPageProps> = ({ user }) => {
  if (!user) {
    return <div>User not found</div>;
  }
  return (
    <div className="container">
      <h1>{user.name}</h1>
      <p>{user.email}</p>
    </div>
  );
};

export default UserPage;

// packages/nuxt-app/pages/users/[id].vue
<template>
  <div>
    <div>detail</div>
    <h1>{{ user.lastName }}</h1>
    <p>{{ user.email }}</p>
  </div>
</template>


<script setup lang="ts">
import { useRoute, useAsyncData } from 'nuxt/app'

// TypeScriptインターフェースの定義
interface User {
  id: string;
  lastName: string;
  email: string;
}

// ルートからパラメータを取得
const route = useRoute()
const { id } = route.params as { id: string }

// データフェッチ
const { data: user, pending, error } = await useAsyncData<User>('fetchUser', () =>
  fetch(`https://dummyjson.com/users/${id}`).then(res => {
    if (!res.ok) {
      throw new Error('ユーザーを取得できませんでした')
    }
    return res.json()
  })
)

// エラーハンドリング
if (error.value) {
  console.error(error.value)
}
</script>

<style scoped>
.container {
  padding: 20px;
}
</style>
