// packages/nuxt-app/components/RegisterForm.vue
<template>
  <form @submit.prevent="register">
    <input v-model="name" type="text" placeholder="Name" required />
    <input v-model="email" type="email" placeholder="Email" required />
    <button type="submit">Register</button>
    <p v-if="message">{{ message }}</p>
  </form>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import axios from 'axios';

export default defineComponent({
  setup() {
    const name = ref('');
    const email = ref('');
    const message = ref('');

    const register = async () => {
      try {
        const res = await axios.post('/api/register', {
          name: name.value,
          email: email.value,
        });
        if (res.data.success) {
          message.value = 'Registration successful!';
        }
      } catch (error) {
        console.error(error);
        message.value = 'Registration failed.';
      }
    };

    return { name, email, register, message };
  },
});
</script>

// packages/remix-app/app/components/RegisterForm.tsx
import { Form, useActionData } from '@remix-run/react';

interface ActionData {
  success?: boolean;
  error?: string;
}

const RegisterForm: React.FC = () => {
  const actionData = useActionData<ActionData>();

  return (
    <div>
      <Form method="post" action="https://your-api-endpoint.com/register">
        <input type="text" name="name" placeholder="Name" required />
        <input type="email" name="email" placeholder="Email" required />
        <button type="submit">Register</button>
      </Form>
      {actionData?.success && <p>Registration successful!</p>}
      {actionData?.error && <p>{actionData.error}</p>}
    </div>
  );
};

export default RegisterForm;
